# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='decription',
            new_name='description',
        ),
    ]
